server:
  port: 8013

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: off
  application:
    name: swagger-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka