spring:
  application:
    name: Eureka-Discovery-Client

server:
  port: 8011

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, env, beans, loggers
        exclude:
          - threaddump
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka