spring:
  application:
    name: Cloud-Config-Client-App
  config:
    import: optional:configserver:http://localhost:8013

server:
  port: 8014

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure: "*"